apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
<<<<<<< HEAD
          image: ghcr.io/samir120/swadestack-backend:7dc9fc4315d8e83a74db22d77bec9f84dcccb3d7
=======
          image: ghcr.io/samir120/swadestack-backend
>>>>>>> 5f1dfc2 (Move staging image tags to overlay)

          command:
            - npm
            - run
            - db:migrate:production

          envFrom:
            - secretRef:
                name: swadestack-secrets
            - configMapRef:
                name: swadestack-config
