---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgB0Nqcpvu4TbHh7/9kNGo2PfpL58cfJj3ghY90ea7xNJWTqZ6QrIgYqN3/IefNiD2heFiNCBJtU01nJFdxQzB4yJ5kL+wPO3KnSpMEFBSmHhFgpfX2dEtKa1R/efjxEJ+CaKz0rCsNO2FIzT6uPiGwJlO1trFCRKAQwjSyqG9tp/ylfGrZiWkKRRAeOcVw5HvPtSEHvwTrcK9t8+z6IbhA3hlL5Wx/Vb8aQ1l0800YIXD38wIfo2lib1kWlO92fGelmIzgX9RiuLTOvOAX62rc8ZErhSbDtLn5gmcpwDHkPt6r9lwtO9wm2PlYE1e4qxPU05YFiIvt4aQaA/68Tn/D3pbRJ3+rr6cqvbkoDd2aYRyfkLKI/cxJt8auM8BQbYjb+p2cZ51JDXl3i8QWz6E9Tq7cX42Xflmik/fzLcAPfGUiOg2QtBwcP9sOOqL4LQpKhFHsf4R/y7qbzsorXlc4PF9KDUqKYqqVMOBtLwvTmgMAanDYHZQepyepNvz2UjHn8pvQRh8wxgJxmV7uVd6PYVDIXMD762xLa9AbCIUnGbPCdZLiK0qsC1wP6CqHy2sTCTcmy/Oxa53LnVfl6uc5psYDwDBVDaMq3fgJx/uxuIh1OrNH9vHu4/UQFZ16JR17LZbFY+JoDcwM+lYUUkA9K/AD5JQkQkXv0TUHp9xmCnKRaLFHnaOP6OfuLVB9hUN4GOn0mdzlMjgrcG0vxs0BROPJp+Uti3GqutV7WYQQVvU7Rze14y2BMBZBjoXiSGUYzgMSTFqdreS1OLq7132KdPqMPbdJ3QXZUU1vpFVOGi/XOKopYdVn7XCw0piAb3w1H80MiXqHI5cy5CIary69SjyCbGRLDc8dB5CCepbMowQHLjmuM0nDTovx0zxVEg/ILmtf3v3j2sHdsJDnoxix4HE0cWgze1P8LWjZ9fBKwDPzXIB8ZO79u
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
