apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swadestack-staging

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - ingress.yaml

images:
  - name: ghcr.io/samir120/swadestack-backend
    newTag: 9672a0cfd34a0ddaa0ec9a9addf2906bbeb0bb0c

  - name: ghcr.io/samir120/swadestack-frontend
    newTag: 9672a0cfd34a0ddaa0ec9a9addf2906bbeb0bb0c
