apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swadestack-staging

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - ingress.yaml

images:
  - name: ghcr.io/samir120/swadestack-backend
    newTag: 0b2226c42e1b7ebd0454a7da58b12c7b34883264

  - name: ghcr.io/samir120/swadestack-frontend
    newTag: 0b2226c42e1b7ebd0454a7da58b12c7b34883264
