---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
spec:
  encryptedData:
    password: AgAz3ZRjxW8p1t/2ZrcFSmHSsoWxPbrjH560VicSWAadAe4oTsghVAY/HqDI7XJdS2dnEU7+V8fI0uWc9NHSxaRdSG9Pf7wBAwD0aBKTxUbMnSpyQKNFcJWeQFx+D/XGPPctXTiHrUYzuAypwvnrjiCg4KVmcvs6pNNZEhAkeme5I7zXz8ui7xKZ+3af9YSvDpoYM5FW1HDqd11J0AVAhtchHy4nmSwvLD0/t/mwE7i4byV0UlYapGF8fkfmBOtYkH7aqqQrRJq0EqBPuNMjEh8UNbed5++GerYNDdtvsKyPWYsAu9Lnt06fQvTXyXVXVla2rwHZZB4V3o3gtfliHczVMr69UNLOqErYxAjArLNeoxIkZ5sFzHEdH0CKozAGtRcEvPNoztA8oQauEM/FBijaPbBUL5gLOUoP9NFpcGt5SgKpeoksyR/uqhu35kOoNuw8uKktx76tozoGhWV4rDNF1Qfr3q3mbJdXoXiV+hyqobRQU0hn4CjWyjNiy+L5lAdf3EnblUj4ck4tH3rwy+viqz0J9FQg0smayPAlqCPK7V1tUcW01dQVUD6o4AM1a6zYurWK2ojql5NYJQsuLqe63VivDQn9nwP3VCOJX/l3jcGAtET46saYvE0ajIriPADE/mcCpPUkffgYTmcIH+OitYTz+Z9bZkLQjG8Bej2zEZqBLA5sND/iYCK8SMTk+1Mj572gW0wInGwJoECGM5VD6cScj755Zj/EtCkB9QGQnYRsZt+Nvs181sOB2F2cUxK9p+ZJqoQkamnnKG6f+KZqDu7vCbl/1VDAJUFSgPcXRgMZnsvI4JvXhsE=
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
