---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
spec:
  encryptedData:
    password: AgB+uLZSXqn8+hc5jNxtHI1/6p7enfBxyoKd4UZwdSZcUg3wMwWn8XyKMiH0mEPi3hdmSh9sojzF+QM/aEePUjEnNURqP9lDt0pu8vmX/xMCiGmT8M48BaorqhO85zoZDANs444qFs+svR8/oZ5dmdzQwcKhFIkRlpRe759q9TeB91vWxn9SaMeQQrJfwEq2OdELiYCmc+Q+qHXSV0bnb13rOJfKVxBwTBWfrf4w3Rd07pg2do+UfxiCJJ2mF6ci14ZU7xl7Si5FKAQM6kdmbpcSGpzXW8AkybmiuCHxMQFVfDKEW8VM/7HODJ0jensHs9bEZd+O+PNRGf2bxWJWTvT8xxic/0KJoy4HqhK5p3gODpA8XXkNRTrsgXg9ORlQH5FVSP8WDkiPYuz6gDBLyl75FbhsEk3kXdpjoLmhs3loRO3Z5M8kyX93ak2OWpdlepS+rdj1VuEZS0hXnbf3bW2UrT4q2pS+erxsKkmGrMXyjVJVH3FOZHHcaLPKG/PHoTwnlCQwQ1pxcFUCjeaCkZ0CQmbZRylYAxhnS7cp+71+8VJZtNviBGqBh4KEDiuZvt95xrGtGyUYHbnSdb+rJAndhp9m1ePdQZA3ZR720WD39NzllSoGrdb9wuuY4O3+uSVuRR+HkxyE1RrV6Lwuxhl2vAR1IVwTweJ2/TCuY/L0cMajrLYru5DwYoR1KqjX3HMzSbANVWBVxaUK2mSIXnWPHfJctT2upQXXtMTa0j2Z0w95y6CPS6j9J2NftXPt+GY0ZUY11ydCCOV++RFO5+JV7mLTxMh6O6LndBf84C9KJzhXtEvMdoS3nnQ=
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
