apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - swadestack-probes.yaml
  - swadestack-alerts.yaml
  - alertmanagerconfig.yaml
  - alertmanager-smtp-sealedsecret.yaml
  - test-alert.yaml
