apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: swadestack-production
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobName: swadestack-production

  interval: 30s
  module: http_2xx

  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - https://swadestack.com
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: swadestack-staging
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobName: swadestack-staging

  interval: 30s
  module: http_2xx

  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - https://lab.swadestack.com
