apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swadestack-backups
  namespace: swadestack-production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
