apiVersion: v1
kind: ConfigMap
metadata:
  name: swadestack-config
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  NODE_ENV: production
  PORT: "5000"

  DB_HOST: postgres
  DB_PORT: "5432"

  FRONTEND_URL: https://swadestack.com
  CORS_ORIGIN: https://swadestack.com

  KLARNA_API_URL: https://api.playground.kustom.co
  KLARNA_TERMS_URL: https://swadestack.com/terms
  KLARNA_CHECKOUT_URL: https://swadestack.com/klarna-checkout/{checkout.order.id}
  KLARNA_CONFIRMATION_URL: https://swadestack.com/order-confirmation/{checkout.order.id}
  KLARNA_PUSH_URL: https://swadestack.com/api/orders/klarna/push

  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_SECURE: "false"

  APP_NAME: Swadestack
