apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swadestack-production

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - ingress.yaml

images:
  - name: ghcr.io/samir120/swadestack-backend
    newTag: e542ba6ae754c80b95c0eb99910716e27af2e869

  - name: ghcr.io/samir120/swadestack-frontend
    newTag: e542ba6ae754c80b95c0eb99910716e27af2e869
