apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swadestack-production

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - ingress.yaml
  - backup-pvc.yaml
  - db-backup-cronjob.yaml
  - uploads-backup-cronjob.yaml

images:
  - name: ghcr.io/samir120/swadestack-backend
    newTag: 283aac150aeef530f499b56ad5680a8b57138157

  - name: ghcr.io/samir120/swadestack-frontend
    newTag: 283aac150aeef530f499b56ad5680a8b57138157
