apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 11.17.1
    helm:
      releaseName: blackbox-exporter
      values: |
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi

        serviceMonitor:
          enabled: true
          selfMonitor:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
